"""Add format for attribute

Revision ID: 05a62958a9cc
Revises: 6c4c02043e82
Create Date: 2019-02-20 09:48:17.126547

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '05a62958a9cc'
down_revision = '6c4c02043e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute',
                  sa.Column('format', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute', 'format')
    # ### end Alembic commands ###
