"""empty message

Revision ID: 0d09368b6717
Revises: 5273835c1a8e
Create Date: 2017-08-11 11:41:15.513238

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0d09368b6717'
down_revision = '5273835c1a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source',
                  sa.Column('is_public', sa.Boolean(), nullable=False,
                            server_default='0'))
    op.add_column('data_source',
                  sa.Column('treat_as_missing', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source', 'treat_as_missing')
    op.drop_column('data_source', 'is_public')
    # ### end Alembic commands ###
