"""empty message

Revision ID: 0eadac2ac523
Revises: 27c524d7f4e6
Create Date: 2017-09-18 15:02:54.324865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eadac2ac523'
down_revision = '27c524d7f4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('class_name', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'class_name')
    # ### end Alembic commands ###
