"""added description column into model table

Revision ID: 0fedcd3af9ff
Revises: c74c284e47e6
Create Date: 2022-12-22 21:55:25.984308

"""
from alembic import op
import sqlalchemy as sa
from limonero.migration_utils import is_sqlite


# revision identifiers, used by Alembic.
revision = '0fedcd3af9ff'
down_revision = 'c74c284e47e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('model') as batch_op:
            batch_op.drop_column('description')
    else:
        op.drop_column('model', 'description')
    # ### end Alembic commands ###
