"""add new fk in model table from datasource

Revision ID: 1b9e3bdce7ef
Revises: cec3c3519efd
Create Date: 2022-12-26 20:06:22.722194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b9e3bdce7ef'
down_revision = 'cec3c3519efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('data_source_id', sa.Integer, sa.ForeignKey('data_source.id')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'data_source_id')
    # ### end Alembic commands ###
