"""permission with user info

Revision ID: 1f797e7ccce7
Revises: 5a14564f944f
Create Date: 2017-06-06 17:17:17.291669

"""
from alembic import op
import sqlalchemy as sa
from limonero.migration_utils import is_sqlite


# revision identifiers, used by Alembic.
revision = '1f797e7ccce7'
down_revision = '5a14564f944f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('data_source_permission') as batch_op:
            batch_op.add_column(sa.Column('user_login', sa.String(length=50), nullable=False, server_default=''))
            batch_op.add_column(sa.Column('user_name', sa.String(length=50), nullable=False, server_default=''))
    else:
        op.add_column('data_source_permission', sa.Column('user_login', sa.String(length=50), nullable=False))
        op.add_column('data_source_permission', sa.Column('user_name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('data_source_permission') as batch_op:
            batch_op.drop_column('user_login')
            batch_op.drop_column('user_name')
    else:
        op.drop_column('data_source_permission', 'user_name')
        op.drop_column('data_source_permission', 'user_login')
    # ### end Alembic commands ###
