""" extra parameters for storage

Revision ID: 3949289c976c
Revises: 0c56a2478a23
Create Date: 2020-06-09 16:19:24.260000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3949289c976c'
down_revision = '0c56a2478a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('client_url', sa.String(length=1000), nullable=True))
    op.add_column('storage', sa.Column('extra_params', mysql.LONGTEXT(), nullable=True))
    op.add_column('data_source', sa.Column('is_lookup', sa.Boolean(), nullable=False))
    op.execute("""
        ALTER TABLE `storage` CHANGE `type` `type` ENUM(
            'CASSANDRA','ELASTIC_SEARCH','HDFS','HIVE', 'HIVE_WAREHOUSE',
             'JDBC','LOCAL','MONGODB'
            ) CHARSET utf8 COLLATE
            utf8_unicode_ci NOT NULL;""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage', 'extra_params')
    op.drop_column('storage', 'client_url')
    op.drop_column('data_source', 'is_lookup')
    op.execute("""
        ALTER TABLE `storage` CHANGE `type` `type` ENUM(
            'CASSANDRA','ELASTIC_SEARCH','HDFS','HIVE','JDBC','LOCAL','MONGODB'
            ) CHARSET utf8 COLLATE
            utf8_unicode_ci NOT NULL;""")
    # ### end Alembic commands ###
