""" extra parameters for storage

Revision ID: 3949289c976c
Revises: 0c56a2478a23
Create Date: 2020-06-09 16:19:24.260000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from limonero.migration_utils import (is_mysql, is_psql, upgrade_actions, 
        downgrade_actions, get_psql_enum_alter_commands, is_sqlite)

# revision identifiers, used by Alembic.
revision = '3949289c976c'
down_revision = '0c56a2478a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('client_url', sa.String(length=1000), nullable=True))
    if is_mysql():    
        op.add_column('storage', sa.Column('extra_params', mysql.LONGTEXT(), nullable=True))
    else:
        op.add_column('storage', sa.Column('extra_params', sa.Text(), nullable=True))
    op.add_column('data_source', sa.Column('is_lookup', sa.Boolean(), nullable=False, 
        server_default='false'))

    if is_mysql():
        op.execute("""
            ALTER TABLE `storage` CHANGE `type` `type` ENUM(
                'CASSANDRA','ELASTIC_SEARCH','HDFS','HIVE', 'HIVE_WAREHOUSE',
                 'JDBC','LOCAL','MONGODB'
                ) CHARSET utf8 COLLATE
                utf8_unicode_ci NOT NULL;""")
    elif is_psql():
        storage_values = ['CASSANDRA','ELASTIC_SEARCH','HDFS',
                'HIVE', 'HIVE_WAREHOUSE', 'JDBC','LOCAL','MONGODB']
        all_commands = [
            [
                get_psql_enum_alter_commands(['storage'], ['type'],
                    'StorageTypeEnumType', storage_values, 'HDFS'),
                None
            ]
        ]
        upgrade_actions(all_commands)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('storage') as batch_op:
            batch_op.drop_column('extra_params')
            batch_op.drop_column('client_url')

        with op.batch_alter_table('data_source') as batch_op:
            batch_op.drop_column('is_lookup')

    else:
        op.drop_column('storage', 'extra_params')
        op.drop_column('storage', 'client_url')
        op.drop_column('data_source', 'is_lookup')

    if is_mysql():
        op.execute("""
            ALTER TABLE `storage` CHANGE `type` `type` ENUM(
                'CASSANDRA','ELASTIC_SEARCH','HDFS','HIVE','JDBC','LOCAL','MONGODB'
                ) CHARSET utf8 COLLATE
                utf8_unicode_ci NOT NULL;""")
    elif is_psql():
        storage_values = ['CASSANDRA','ELASTIC_SEARCH','HDFS',
                'HIVE', 'JDBC','LOCAL','MONGODB']
        all_commands = [
            [
                None,
                get_psql_enum_alter_commands(['storage'], ['type'],
                    'StorageTypeEnumType', storage_values, 'HDFS'),
            ]
        ]
        downgrade_actions(all_commands)

    # ### end Alembic commands ###
