"""Data source initialization

Revision ID: 422f46c29791
Revises: 96581239a707
Create Date: 2019-10-07 20:45:35.783397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422f46c29791'
down_revision = '96581239a707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('initialization', sa.Enum('NO_INITIALIZED', 'INITIALIZING', 'INITIALIZED', name='DataSourceInitializationEnumType'), nullable=False))
    op.drop_index('inx_type', table_name='model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('inx_type', 'model', ['type'], unique=False)
    op.drop_column('data_source', 'initialization')
    # ### end Alembic commands ###
