"""Privacy

Revision ID: 5a14564f944f
Revises: c1124305c79e
Create Date: 2017-06-05 17:02:20.292939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a14564f944f'
down_revision = 'c1124305c79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Enum('READ', 'MANAGE', 'DENY', 'WRITE', name='PermissionTypeEnumType'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_source_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Enum('READ', 'MANAGE', 'DENY', 'WRITE', name='PermissionTypeEnumType'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privacy_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IDENTIFICATION', name='PrivacyRiskTypeEnumType'), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_privacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('privacy_type', sa.String(length=100), nullable=False),
    sa.Column('category_technique', sa.String(length=100), nullable=False),
    sa.Column('anonymization_technique', sa.Enum('MASK', 'GENERALIZATION', 'SUPPRESSION', name='AnonymizationTechniqueEnumType'), nullable=False),
    sa.Column('hierarchical_structure_type', sa.String(length=100), nullable=False),
    sa.Column('privacy_model_technique', sa.String(length=100), nullable=False),
    sa.Column('hierarchy', sa.Text(), nullable=False),
    sa.Column('category_model', sa.Text(), nullable=False),
    sa.Column('privacy_model', sa.Text(), nullable=False),
    sa.Column('privacy_model_parameters', sa.Text(), nullable=False),
    sa.Column('unlock_privacy_key', sa.String(length=400), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'data_source', sa.Column('privacy_aware', sa.Boolean(), nullable=False))
    op.add_column(u'data_source', sa.Column('statistics_process_counter', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'data_source', 'statistics_process_counter')
    op.drop_column(u'data_source', 'privacy_aware')
    op.drop_table('attribute_privacy')
    op.drop_table('privacy_risk')
    op.drop_table('data_source_permission')
    op.drop_table('storage_permission')
    # ### end Alembic commands ###
