"""Add attribute to handle multiline information

Revision ID: 66d4be40bced
Revises: 6a809295d586
Create Date: 2018-05-16 12:13:32.023450

"""
import sqlalchemy as sa
from alembic import op
from limonero.migration_utils import is_sqlite

# revision identifiers, used by Alembic.
revision = '66d4be40bced'
down_revision = '6a809295d586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('data_source') as batch_op:
            batch_op.add_column(sa.Column('is_multiline', sa.Boolean(), nullable=False, server_default='0'))
    else:
        op.add_column('data_source',
                  sa.Column('is_multiline', sa.Boolean(), nullable=False,
                            default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('data_source') as batch_op:
            batch_op.drop_column('is_multiline')
    else:
        op.drop_column('data_source', 'is_multiline')
    # ### end Alembic commands ###
