"""empty message

Revision ID: 7addb7587b1a
Revises: 3949289c976c
Create Date: 2020-09-02 18:08:48.459701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7addb7587b1a'
down_revision = '3949289c976c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('use_in_workflow', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_data_source_use_in_workflow'), 'data_source', ['use_in_workflow'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_source_use_in_workflow'), table_name='data_source')
    op.drop_column('data_source', 'use_in_workflow')
    # ### end Alembic commands ###
