"""Add job initialization id

Revision ID: 7fd1bcffbbc2
Revises: f99e6e92b196
Create Date: 2019-11-28 11:02:44.449174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd1bcffbbc2'
down_revision = 'f99e6e92b196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('initialization_job_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source', 'initialization_job_id')
    # ### end Alembic commands ###
