"""Add data source variables

Revision ID: 88672039047e
Revises: c6f3cb7e343c
Create Date: 2024-04-03 14:08:45.236323

"""
from alembic import op
import sqlalchemy as sa
from limonero.migration_utils import is_psql

# revision identifiers, used by Alembic.
revision = '88672039047e'
down_revision = 'c6f3cb7e343c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not is_psql():
        desc = sa.Column('description', sa.Text(length=4294000000), nullable=True)
        default = sa.Column('default_value', sa.Text(length=4294000000), nullable=True)
    else:
        desc = sa.Column('description', sa.Text(), nullable=True)
        default = sa.Column('default_value', sa.Text(), nullable=True)

    op.create_table('data_source_variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    desc, default,
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], name='fk_data_source_variable_data_source_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_variable_data_source_id'), 'data_source_variable', ['data_source_id'], unique=False)
     # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_source_variable_data_source_id'), table_name='data_source_variable')
    op.drop_table('data_source_variable')
    # ### end Alembic commands ###
