"""add metrics column in model table

Revision ID: 8dcd395193f7
Revises: 1b9e3bdce7ef
Create Date: 2023-02-06 22:35:07.686205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from limonero.migration_utils import is_sqlite

# revision identifiers, used by Alembic.
revision = '8dcd395193f7'
down_revision = '1b9e3bdce7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('metrics', sa.JSON, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('model') as batch_op:
            batch_op.drop_column('metrics')
    else:
        op.drop_column('model', 'metrics')
    # ### end Alembic commands ###
