"""empty message

Revision ID: 8e7d4a324584
Revises: b4cc9e8ef9ca
Create Date: 2017-03-24 15:30:53.434193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e7d4a324584'
down_revision = 'b4cc9e8ef9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('statistics_process_counter', sa.Integer(), nullable=False))
    op.drop_column('data_source', 'statistics_processed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('statistics_processed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('data_source', 'statistics_process_counter')
    # ### end Alembic commands ###
