"""new attributes for csv files

Revision ID: 9dccb02d8201
Revises: 70abcb00e23f
Create Date: 2017-06-30 15:30:33.159354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dccb02d8201'
down_revision = '70abcb00e23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('attribute_delimiter', sa.String(length=4), nullable=True))
    op.add_column('data_source', sa.Column('record_delimiter', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source', 'record_delimiter')
    op.drop_column('data_source', 'attribute_delimiter')
    # ### end Alembic commands ###
