"""Add path property to storage

Revision ID: b0815c138c24
Revises: bdeb80e4de30
Create Date: 2024-06-13 17:11:40.762658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0815c138c24'
down_revision = 'bdeb80e4de30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage', 'path')
    # ### end Alembic commands ###
