"""empty message

Revision ID: b4cc9e8ef9ca
Revises: efa53423306c
Create Date: 2017-03-24 15:23:38.302598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4cc9e8ef9ca'
down_revision = 'efa53423306c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privacy_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IDENTIFICATION', name='PrivacyRiskTypeEnumType'), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_privacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('privacy_attribute_type', sa.String(length=100), nullable=False),
    sa.Column('category_technique', sa.String(length=100), nullable=False),
    sa.Column('anonymization_technique', sa.String(length=100), nullable=False),
    sa.Column('hierarchical_structure_type', sa.String(length=100), nullable=False),
    sa.Column('hierarchy', sa.String(length=100), nullable=False),
    sa.Column('category_model', sa.String(length=100), nullable=False),
    sa.Column('privacy_model', sa.String(length=100), nullable=False),
    sa.Column('privacy_model_technique', sa.String(length=100), nullable=False),
    sa.Column('privacy_model_parameters', sa.Text(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'data_source', sa.Column('privacy_aware', sa.Boolean(), nullable=False))
    op.add_column(u'data_source', sa.Column('statistics_processed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'data_source', 'statistics_processed')
    op.drop_column(u'data_source', 'privacy_aware')
    op.drop_table('attribute_privacy')
    op.drop_table('privacy_risk')
    # ### end Alembic commands ###
