"""Add position column

Revision ID: bdeb80e4de30
Revises: d186003c1c7c
Create Date: 2024-06-03 18:42:01.673580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdeb80e4de30'
down_revision = 'd186003c1c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute', 'position')
    # ### end Alembic commands ###
