"""changed column type into model table from enum to string

Revision ID: cec3c3519efd
Revises: 0fedcd3af9ff
Create Date: 2022-12-24 14:57:08.201168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cec3c3519efd'
down_revision = '0fedcd3af9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model') as batch_op:
        batch_op.alter_column('type', type_=sa.String(length=50))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model') as batch_op:
        batch_op.alter_column('type', type_=sa.Enum('KERAS', 'MLEAP', 'PERFORMANCE_SPARK', 'PERFORMANCE_KERAS',
                                                      'PERFORMANCE', 'SPARK_ML_REGRESSION', 'SPARK_MLLIB_CLASSIFICATION',
                                                      'SPARK_ML_CLASSIFICATION', 'UNSPECIFIED'))
    # ### end Alembic commands ###

