"""Add raw_type column

Revision ID: d186003c1c7c
Revises: 66581239a707
Create Date: 2024-05-29 18:13:55.995557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd186003c1c7c'
down_revision = '66581239a707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('raw_type', sa.String(length=100), nullable=False))
   # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute', 'raw_type')
    # ### end Alembic commands ###
