"""Data source types

Revision ID: f99e6e92b196
Revises: 422f46c29791
Create Date: 2019-11-11 09:09:53.296011

"""
from alembic import op
from sqlalchemy.sql import text
from limonero.migration_utils import (get_enable_disable_fk_command,
        upgrade_actions, downgrade_actions, get_psql_enum_alter_commands,
        is_mysql)

# revision identifiers, used by Alembic.
revision = 'f99e6e92b196'
down_revision = '422f46c29791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_foreign_key('attribute_privacy_attribute_id_fk', 'attribute_privacy', 'attribute',
                          ['attribute_id'], ['id'], ondelete='CASCADE')
    if is_mysql():
        op.get_bind().execute(text("""
            ALTER TABLE data_source
            CHANGE COLUMN `format` `format` ENUM(
                'CSV', 'CUSTOM', 'GEO_JSON', 'HAR_IMAGE_FOLDER', 'HDF5',
                'DATA_FOLDER', 'IMAGE_FOLDER', 'JDBC', 'JSON', 'NETCDF4', 'NPY',
                'PARQUET', 'PICKLE', 'SAV', 'SHAPEFILE', 'TAR_IMAGE_FOLDER', 'TEXT',
                'VIDEO_FOLDER', 'UNKNOWN', 'XML_FILE')
                CHARACTER SET 'utf8' NOT NULL ;"""))
    else:
        new_ds_values = ['CSV', 'CUSTOM', 'GEO_JSON', 'HAR_IMAGE_FOLDER', 'HDF5',
                'DATA_FOLDER', 'IMAGE_FOLDER', 'JDBC', 'JSON', 'NETCDF4', 'NPY',
                'PARQUET', 'PICKLE', 'SAV', 'SHAPEFILE', 'TAR_IMAGE_FOLDER', 'TEXT',
                'VIDEO_FOLDER', 'UNKNOWN', 'XML_FILE']
 
        all_commands =  [[
                get_psql_enum_alter_commands(['data_source'], ['format'], 
                    'DataSourceFormatEnumType', new_ds_values, 'CSV'),
                None
            ]]
        upgrade_actions(all_commands)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('attribute_privacy_attribute_id_fk', 'attribute_privacy', type_='foreignkey')

    if is_mysql():
        op.get_bind().execute(text("""
            ALTER TABLE data_source
            CHANGE COLUMN `format` `format` ENUM(
                'CSV', 'CUSTOM', 'GEO_JSON', 'HAR_IMAGE_FOLDER', 'HDF5',
                'DATA_FOLDER', 'IMAGE_FOLDER', 'JDBC', 'JSON', 'NETCDF4',
                'PARQUET', 'PICKLE', 'SHAPEFILE', 'TAR_IMAGE_FOLDER', 'TEXT',
                'VIDEO_FOLDER', 'UNKNOWN', 'XML_FILE')
                CHARACTER SET 'utf8' NOT NULL ;"""))
        # ### end Alembic commands ###
    else:
        old_ds_values = ['CSV', 'CUSTOM', 'GEO_JSON', 'HAR_IMAGE_FOLDER', 'HDF5',
                'DATA_FOLDER', 'IMAGE_FOLDER', 'JDBC', 'JSON', 'NETCDF4',
                'PARQUET', 'PICKLE', 'SHAPEFILE', 'TAR_IMAGE_FOLDER', 'TEXT',
                'VIDEO_FOLDER', 'UNKNOWN', 'XML_FILE']
        all_commands =  [[
                None,
                get_psql_enum_alter_commands(['data_source'], ['format'], 
                    'DataSourceFormatEnumType', old_ds_values, 'CSV'),
            ]]
        downgrade_actions(all_commands)


